### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by guglovich** [ishitatsuyuki/LatencyFleX#13]
Checked everything according to the guide. 
https://github.com/ishitatsuyuki/LatencyFleX/blob/master/docs/TROUBLESHOOTING.md
At the end of the log file is :

```
../builtin.cpp: Querying MemoryWineUnixFuncs failed c0000135
../builtin.cpp: Look for library loading errors in the log and check if liblatencyflex_layer.so is installed on your system.
```
latencyflex_layer.so is in /usr/lib/wine/x86_64-unix/ and /usr/lib64/wine/x86_64-unix/, and liblatencyflex_layer.so is also in /usr/lib/

**Comment by guglovich** [comment]
[steam-1172470.log](https://github.com/ishitatsuyuki/LatencyFleX/files/8592253/steam-1172470.log)

**Comment by ishitatsuyuki** [comment]
If you are running proton, you need to put latencyflex_layer.so inside the Proton lib directory. That should fix it.

**Comment by guglovich** [comment]
> If you are running proton, you need to put latencyflex_layer.so inside the Proton lib directory. That should fix it.
You mean the folder? Didn't work
SteamLibrary/steamapps/common/Proton - Experimental/files/lib

**Comment by ishitatsuyuki** [comment]
Please refer to the instructions from README.

https://github.com/ishitatsuyuki/LatencyFleX#latencyflex-wine-extensions-required-for-proton-reflex-integration

What I meant is lib64/wine/x86_64-unix.

**Comment by guglovich** [comment]
It said /usr/lib/wine, I copied everything correctly there, but with Proton it's not very clear, in /.local/share/Steam/steamapps/compatdata/<appid>/pfx where those folders aren't there or somewhere deeper.

**Comment by ishitatsuyuki** [comment]
So did you get it right? It's `SteamLibrary/steamapps/common/Proton - Experimental/files/lib64/wine/x86_64-unix`. And the filename is `latencyflex_layer.so` (and not `liblatencyflex_layer.so`).

**Comment by guglovich** [comment]
> So did you get it right? It's `SteamLibrary/steamapps/common/Proton - Experimental/files/lib64/wine/x86_64-unix`. And the filename is `latencyflex_layer.so` (and not `liblatencyflex_layer.so`).

Yes.
![изображение](https://user-images.githubusercontent.com/54148165/166112580-2cd414db-918b-4a6a-a7d9-cde5924ec6c1.png)

**Comment by ishitatsuyuki** [comment]
Is it working now? If so, please close the issue.

**Comment by guglovich** [comment]
> Is it working now? If so, please close the issue.

It's not working yet.

**Comment by ishitatsuyuki** [comment]
Please post an updated log.

**Comment by guglovich** [comment]
[steam-1172470.log](https://github.com/ishitatsuyuki/LatencyFleX/files/8597269/steam-1172470.log)

**Comment by intrntbrn** [comment]
i had the same issue (missing liblatencyflex_layer.so) and this fixed it for me:

```
cp liblatencyflex_layer.so ~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/lib64
cp liblatencyflex_layer.so ~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/lib
```

**Comment by guglovich** [comment]
> i had the same issue (missing liblatencyflex_layer.so) and this fixed it for me:
> 
> ```
> cp liblatencyflex_layer.so ~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/lib64
> cp liblatencyflex_layer.so ~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/lib
> ```

Thanks, one of the two folders was missing a file. Today after all this time I decided to double-check all the folders again and I noticed that I was missing files in /home/user/.local/share/Steam/steamapps/compatdata/1493710/pfx/drive_c/windows/system32/.

Everything works now.
In the future I hope for a simpler installation, e.g. you could arrange the folders in the archive so that they are similar to the paths to be copied into the system.
And, of course, waiting for the integration for MangoHud to keep track of whether LFX is activated.
