### ISSUE TITLE
Deep Rock Galactic support

### ISSUE THREAD

**Issue by neilunger** [ishitatsuyuki/LatencyFleX#17]
As of 6 days ago, [Deep Rock Galactic supports Nvidia Reflex](https://store.steampowered.com/news/app/548430/view/3353506085821721382).

However, I enabled LatencyFlex, and once I click "continue" on the initial loading screen, the game freezes and crashes during the "initializing" splash screen while loading into the spacerig. Disabling Mangohud causes the crash to go away, but Nvidia Reflex is still greyed out in-game, despite having it working with the same launch options and same proton version as Apex, where it is working fine.

The option stayed greyed out no matter if I selected DX11 vs DX12, fullscreen vs borderlerss windows, fps cap enabled vs disabled, etc. V-sync was disabled for all testing.

I know it's not a competitive game, so reflex isn't too necessary, but still neat that another linux game has it.

**Comment by ishitatsuyuki** [comment]
Please go through the [troubleshooting guide](https://github.com/ishitatsuyuki/LatencyFleX/blob/master/docs/TROUBLESHOOTING.md) and provide a log when reporting any issues.

**Comment by neilunger** [comment]
I was missing the dxvk.conf file, as well as the symbolic links in pfx/drive_c. It works! Still crashes when mangohud is enabled, but works! Thanks!

**Comment by neilunger** [comment]
I've now played 2-3 hours (maybe 5 games) of Deep Rock Galactic with LatencyFlex / Reflex enabled, and despite a few issues, it seems to work very well.

I previously mentioned that the game will crash (and freeze up my entire system for about 20-30 seconds) if Mangohud is enabled. I also experienced the the 20fps issue (#16) one time in my 5 games (right after loading into a mission -- once in 2-3 hours is very manageable though), and the Steam Overlay Shifting issue (#9).

Despite these issues, it seems to work incredibly well. @ishitatsuyuki do you consider this working well enough to put it in the "Tested/Support Games" table in the readme?

**Comment by ishitatsuyuki** [comment]
Sounds good, make a PR and I will accept it. Otherwise I will add it later when I get back to this.
