### ISSUE TITLE
Does LatencyFlex work on Wayland?

### ISSUE THREAD

**Issue by hurricane-dorian** [ishitatsuyuki/LatencyFleX#18]
Does it work with mailbox presentation mode or does it have to wait till Wayland implements immediate presentation a.k.a tearing?

**Comment by ishitatsuyuki** [comment]
It works with mailbox. Generally it works as long as your compositor doesn't interfere in a way that caps your FPS.

**Comment by ishitatsuyuki** [comment]
Closing as this seems to have answered your question.
