### ISSUE TITLE
AUR packages compiled but dll's and so wrong file size

### ISSUE THREAD

**Issue by TropicZL1** [ishitatsuyuki/LatencyFleX#23]
Installed LFX from AUR and was fighting to get it to work for hours. Decided to start from scratch and just manually install everything. When I downloaded the files from repo I noticed that the file sizes were dramatically different. latencyflex_layer.dll from AUR was 50B but my manual download was 189.2KiB and my latencyflex_wine.dll from AUR was 49B while my manual download was 30.8KiB just as an example. Other files had the same discrepancy, not 100% sure what the issue is with AUR. I can recompile and provide the files if necessary.

**Comment by ishitatsuyuki** [comment]
If your compiler or build tools are emitting 50B binaries there's an issue with your MinGW or Wine installation. Even the PE header wouldn't fit in that. Try `strings <file>` and see what's in it?

As usual, you _should_ be able to build without problem with stock Wine and MinGW from Arch repositories.

**Comment by TropicZL1** [comment]
Double-checked Wine and MinGW just to be sure and did a clean build from AUR. This time the files created were the right size and Nvidia Reflex works ingame. Perhaps a fluke the first time building? Whatever the case may be everything is working now. Thanks for the fast response! If it happens again I'll be sure to save the built files separately for you to analyze.
