### ISSUE TITLE
Apex Legends - Wine bridge fails to initialize with seemingly no error message

### ISSUE THREAD

**Issue by deltainium** [ishitatsuyuki/LatencyFleX#25]
Hello, hope you're doing well.
I've managed to successfully install LatencyFleX for Overwatch 2 but for some reason Apex Legends has been giving me a some trouble. 

**Troubleshooting steps taken**
- I have triple checked that I installed everything correctly from the install instructions
- I have gone through the [troubleshooting step](https://github.com/ishitatsuyuki/LatencyFleX/blob/master/docs/TROUBLESHOOTING.md) and nothing has been applicable up until "Checking if the Wine bridge successfully initialized"
I see that `Loading latencyflex_layer.dll failed with error code: 1114` except unlike the troubleshooting steps guide, the only error code appears to be some unrelated NvAPI_QueryInterface:

**Snippet of log file**
`DXVK_NVAPI_DRIVER_VERSION is set to '49729', reporting driver version 497.29
1326.498:0128:012c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\latencyflex_layer.dll" at 0000000058850000: builtin
1326.498:0128:012c:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\latencyflex_layer.dll" : builtin
Loading latencyflex_layer.dll failed with error code: 1114
NvAPI_Initialize: OK
NvAPI_QueryInterface (0x33c7358c): Unknown function ID
NvAPI_QueryInterface (0x593e8644): Unknown function ID
NvAPI_D3D_SetSleepMode: No implementation
`

Please note that I have verified that both liblatencyflex_layer.so and latencyflex_layer.so have been installed correctly. Furthermore I haven't used a single symlink, every file has been copied manually to its respective install directory. 

**Some info that may be of relevance**
- I am using Proton-GE as opposed to Valve's proton
- Proton-GE is installed onto my main drive, while Apex is installed on a separate drive
- Proton-GE is up to date, so NVAPI v0.6 is installed

Please let me know if there is anything else I can provide to help out. Full log file is attached bellow.
[steam-1172470.log](https://github.com/ishitatsuyuki/LatencyFleX/files/10303215/steam-1172470.log)

**Comment by ishitatsuyuki** [comment]
Hi, can you try finding `toolmanifest.vdf` in your Proton installation dir and replace it with <https://github.com/ValveSoftware/Proton/blob/proton_7.0/toolmanifest_noruntime.vdf>? That should disable the Steam container runtime which has been causing loading failures for some.

**Comment by deltainium** [comment]
Worked like a charm, thanks a million for the swift reply and the help!
