### ISSUE TITLE
Mangohud displaying metrics values only when Nvidia Reflex is enabled

### ISSUE THREAD

**Issue by dubigrasu** [ishitatsuyuki/LatencyFleX#27]
I'm having Mangohud from "custom-metric" branch installed and working.

If Nvidia Reflex is enabled in game, I can see the latency graph (the green line) and latency values (actual numbers) both updated in real time.
But if Nvidia Reflex is disabled, only the graph (green line) remains working real-time, while the latency numbers displayed are stuck to the last whatever values they had when NR was enabled. 
Ideally I'd like to see the latency values still displayed and updated real-time even when NR is not enabled, so I could compare the latencies in both situations.
I'm not sure if this is a bug, or something not implemented.

**Comment by ishitatsuyuki** [comment]
This is working as intended. With Reflex disabled the sleep callback doesn't get called which means we don't really get to measure the latency.

**Comment by dubigrasu** [comment]
Understood, thank you.
