### ISSUE TITLE
Whats the difference between installing it from the aur and manualling installing it.

### ISSUE THREAD

**Issue by hammyexe** [ishitatsuyuki/LatencyFleX#32]
Sorry stupid question, but I was watching a video and he used yay to install it then also downloaded the release file and copied the files to their respective locations. So I was confused; if you install via yay do you need to do the manual install or vice versa? Sorry I am new to linux.

**Comment by ishitatsuyuki** [comment]
You need to copy certain files to your Proton installation since they reside under your Steam library, not the root filesystem. See also notes after installation https://aur.archlinux.org/cgit/aur.git/tree/latencyflex-wine.install?h=latencyflex-git#n2.

**Comment by hammyexe** [comment]
So if I installed  it and didnt copy the files, what would be installed?
