### ISSUE TITLE
How to use on Fedora silverblue / Steam Flatpak

### ISSUE THREAD

**Issue by Racsuu** [ishitatsuyuki/LatencyFleX#34]
Hi, since I'm using silverblue and steam flatpak I'm triying to get latencyflex working, since there is not a flatpak for it like mangohud (and sorry if there is something in work) are there any chance to get it working with steam flatpak? Like adding some permission or something like it.

I install latencyflex vulkan layer via a copr, but i'm not really sure if the vulkan layer installation is the same on silverblue.

Proton files are all fine, use to use it on a nobara install

**Comment by deltainium** [comment]
#7 might be worth a read. If I recall correctly there was mention of a workaround on reddit though Im not sure if its strinctly related.
Also a flatpak install for latencyflex is being [worked on](https://github.com/orowith2os/latencyflex-flatpak) by @orowith2os and @KyleGospo

**Comment by KyleGospo** [comment]
@orowith2os some of the dependencies have been removed since we last spoke, may be easier now.

In the meantime you can layer LatencyFleX with my Copr or use Distrobox instead of flatpak Steam.

**Comment by Racsuu** [comment]
Just a quick update for anytime who need it, the fix for flatpak steam was the next one:

Move latencyflex.json to  `~/.var/app/com.valvesoftware.Steam/.local/share/vulkan/implicit_layer.d/`
Move liblatencyflex_layer.so to `~/.var/app/com.valvesoftware.Steam/.local/lib/x86_64-linux-gnu` (you will have to make by yourself the last two folders)

It is important to edit latencyflex.json to change "library_path" accordingly.

Then all should be working fine if you install the proton extensions and all the other steps, test it on Apex Legends, working 100%

The Reddit comment was not very clear and was missing some stuff, so hopefully this can help someone
