### ISSUE TITLE
Possible Apex ban due to LFX launch options

### ISSUE THREAD

**Issue by neilunger** [ishitatsuyuki/LatencyFleX#38]
So far this is an unconfirmed theory, but I wanted to bring it to your attention.

You may be aware that over the past week, Apex falsely banned a lot of linux players, and as of this morning, has unbanned the vast majority of them (including me, thankfully).

However, there is one user going by R4csu who was not unbanned, and sticks out. R4csu is the only user who used these two launch options: `DXVK_NVAPI_DRIVER_VERSION=49729 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 %command%`
 
Other LFX users were thankfully unbanned, but they did not have those specific launch options. I'm certainly not an expert, but is it possible these options caused the anti-cheat to fail some sort of "graphics driver integrity check" which resulted in R4csu's ban?

Important to note that R4csu was already using an Nvidia GPU, so those launch options are not necessary for LFX to work. R4csu was also banned about a month ago, where most of the other users were banned much later (on/after the night of Aug 17th). Due to R4csu's persistent enthusiasm about getting themself and others unbanned, I would be very surprised if they actually cheated.
 
I have linked my EA Forums comment which goes into slightly more detail. If you'd like me to remove the "hey Respawn, consider integrating LFX into the game" part, or if you have issues with anything else I said, let me know: https://answers.ea.com/t5/Technical-Issues/Linux-players-getting-banned/m-p/12888686/highlight/true#M176231

**Comment by ishitatsuyuki** [comment]
Unfortunately no one really know why the EAC banning incident, and it’s all speculations. I do not and cannot confirm which customizations can lead to a ban, and if EAC is even willing to contact such thing will be done over a private channel.

NVAPI spoofing is unlikely to cause issues if they are already using an NVIDIA GPU. In that case the vendor ID matches, and that sounds way less problematic than faking an NVIDIA GPU out of an AMD GPU.
