### ISSUE TITLE
Add support for Counter-Strike 2

### ISSUE THREAD

**Issue by adamnejm** [ishitatsuyuki/LatencyFleX#40]
Would it be possible to support the native version of Counter-Strike 2?

**Comment by ishitatsuyuki** [comment]
Unless it has Reflex support built-in, no. Anything else involves direct binary hooking which is indistinguishable from a cheat.

**Comment by adamnejm** [comment]
The new installment of Counter-Strike does indeed have Nvidia Reflex support, "naturally" you can only use it on Windows, on Linux the option is unavailable.

**Comment by ishitatsuyuki** [comment]
And it follows that the only way LFX can possibly work is by running on Proton, although I have no idea if they support VAC there.

**Comment by adamnejm** [comment]
I see, the game can apparently be ran on Proton and work with VAC as long as the entire Steam is installed via Flatpak.
I don't think many players will be interested in playing Counter-Strike via Proton however.

Thanks for the answer!

**Comment by Fxzzi** [comment]
I am seeing the Nvidia Reflex option showing in game. Running native with nvidia rtx 3070. No latencyflex installed or running. Can anyone give any info on whether it's actually working?
