### ISSUE TITLE
Witcher 3: Wild Hunt

### ISSUE THREAD

**Issue by In-line** [ishitatsuyuki/LatencyFleX#41]
Hi, so the in game option for Wither 3: Wild Hunt for NVIDIA Reflex isn't available. I redid installation steps several time, tried toolmanifest_noruntime.vdf hack, tried to copy files, do hard links, symlinks. Nothing works. 

```
18744.260:013c:0140:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\latencyflex_layer.dll" at 0000000066280000: builtin
Successfully loaded latencyflex_layer.dll
LatencyFleX loaded and initialized successfully
NvAPI_Initialize: OK
NvAPI_QueryInterface (0x33c7358c): Unknown function ID
NvAPI_QueryInterface (0x593e8644): Unknown function ID
NvAPI_EnumPhysicalGPUs: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_GPU_GetArchInfo: NVIDIA or other suitable device not found or initialization failed
```

[steam-292030.log](https://github.com/ishitatsuyuki/LatencyFleX/files/12811699/steam-292030.log)

**Comment by ishitatsuyuki** [comment]
This is a known problem with Streamline-based games and for now they will only work on NVIDIA GPUs (it asks for actual GPU generation info which needs to be spoofed). You should probably report this at upstream dxvk-nvapi.

**Comment by In-line** [comment]
@ishitatsuyuki Thanks for the fast response. Keep working on this great project!
