### ISSUE TITLE
Ghostrunner: Project Hel - Reflex greyed out

### ISSUE THREAD

**Issue by k9bbzJavftZaqAqSW3dY** [ishitatsuyuki/LatencyFleX#6]
Hi,
first of all this is such a wonderful piece of code. I really enjoy it in Apex Legends and the old version of Ghostrunner.

Now since the Project Hel DLC update for Ghostrunner, the Reflex option that was working right before the update (I replayed it a day ago) is now greyed out. There hasn't been a proton update inbetween, and I double checked that the .so and .dll files are in place. reflex still works for me in Apex Legends.

I checked the logs as per your troubleshooting guide:
- There are no DXVK_NVAPI Device, Output, Version and Initialize messages at all.
- This is also missing: `trace:loaddll:build_module Loaded L"C:\\windows\\system32\\latencyflex_layer.dll" at <address>: builtin`
- This is missing too: `Loading latencyflex_layer.dll failed with error code: 1114`

**Comment by ishitatsuyuki** [comment]
I can confirm that the update seems to have broke LFX support. For me, I have all the NVAPI logs and the layer module is properly loaded, so you might have something wrong in the setup nevertheless.

My guess is that they started requiring several functions that are not strictly necessary and omitted in LFX implementation, but it's time for me to sleep today. I'll investigate tomorrow and keep you updated.

**Comment by Etaash-mathamsetty** [comment]
any updates?

**Comment by ishitatsuyuki** [comment]
I've got it to the point where the button is no longer grayed out but I simply can't get the relevant callbacks to be called if it says "enabled" in the settings screen. Just in case if the devs ended up wiring the Reflex option to *nothing*, I'd appreciate if anyone with Nvidia on Windows can check if the Reflex option in the latest patch makes a difference with the GFE overlay.

**Comment by ishitatsuyuki** [comment]
I debugged the game and I'm pretty sure the dev just forgot to wire the option to execute the correct UE command. The Reflex plugin is still registered so you might be able to enable by using some cheat / console unlocker then set `ReflexMode=1` in console.
