### ISSUE TITLE
LFX=1 shifts steam overlay to the right and halfway off of screen in Apex Legends

### ISSUE THREAD

**Issue by neilunger** [ishitatsuyuki/LatencyFleX#9]
My launch options for Apex Legends are: 
`PROTON_LOG=1 DXVK_NVAPI_LOG_LEVEL=info PROTON_ENABLE_NVAPI=1 LFX=1 gamemoderun %command% -novid +fps_max 180`

This results in the following happening to the Steam overlay:
![Screenshot from 2022-03-17 21-57-11](https://user-images.githubusercontent.com/31961516/158929710-0ed112be-c745-45e6-9da2-f94489b42eda.png)

Once I remove `LFX=1` from the launch options, this no longer happens.

Some possibly important things to note: I have Mangohud globally enabled through GOverlay. I'm playing on a 1440p, 144hz X11 session on Pop!_OS 21.10, with the Steam .deb package (not flatpak) on the latest version of Proton Experimental. I have a second 1080p monitor configured to be to the left of my main 1440p monitor. I've attached my Proton log file, which should include the DXVK_NVAPI_LOG_LEVEL=info information as well.

[lfx_breaking_steam_overlay_proton.log](https://github.com/ishitatsuyuki/LatencyFleX/files/8300093/lfx_breaking_steam_overlay_proton.log)

Let me know if I can provide any other forms of debug information, or do any kind of testing/debugging for you.

**Comment by ishitatsuyuki** [comment]
Thanks for reporting this. I'm running a single monitor 1440p setup and has never seen this, so I'm unfortunately unable to reproduce this right now. I'll keep this issue in mind and update you when I find any potentially related causes.

**Comment by neilunger** [comment]
Thanks, updated the title to be a little more descriptive in case anyone else encounters the issue.

**Comment by ryao** [comment]
I have a 4K monitor. I cannot reproduce this.

**Comment by sehraf** [comment]
I was wondering what is causing this :smile: 
I have two 1440p monitors and it looks like the overlay is stretched across both. I'm on Arch with Steam nativ (LatencyFleX is apparently not working but this is another issue, i do use have `LFX=1`). Similar, when removing `LFX=1` (or setting it to `0`) the overlay fits again.

Since my right monitor is wider than @neilunger's my overlay is stretched more.
![Bildschirmfoto vom 2022-04-22 09-37-35](https://user-images.githubusercontent.com/2230104/164631769-7de2cff3-5d7b-467d-979f-aa6733bdfed6.png)

**Comment by neilunger** [comment]
Glad to see I'm not the only one. I did some testing, Mangohud being globally enabled (or just enabled) makes no difference. What DID make a difference was unplugging my secondary monitor, and then restarting my game. After that, the Steam Overlay was realigned properly.

If I plug my secondary monitor back in while the game is still running, the Steam Overlay is still aligned properly, but I had odd mouse issues in game (possibly unrelated, the game seemed unhappy and reverted from fullscreen to windowed). After restarting my game, the Steam Overlay is again misaligned.

I also tested having my secondary monitor configured to be the left of my main display (where it usually is) versus to the right of my main display, and that also made no difference. It was shifted to the right in both cases.

**Comment by neilunger** [comment]
This issue was fixed for me many months ago, seemingly out of the blue. I'm guessing it was a bug with Steam itself, or maybe an issue with a (now outdated) Pop!_OS package. I will close it, but if someone in the future encounters this, feel free to re-open.
